#!/usr/bin/env python3
"""
Comprehensive Academic Collocation Glossary Generator (832 Terms).
Builds academic_collocation_glossary.json with:
1. Authentic, context-aware academic Vietnamese translations (viGloss).
2. Meaningful, non-boilerplate English explanations (enGloss).
3. Elimination of all literal translation bugs (e.g. professional body -> tổ chức / hiệp hội chuyên môn).
"""

import json
import re
import sys
from pathlib import Path
from typing import Dict, Any

sys.stdout.reconfigure(encoding='utf-8')

ALL_COLLOCS_PATH = Path('scripts/write_essay_support/all_832_collocations.json')
DRAFT_VI_PATH = Path('scripts/write_essay_support/all_832_draft_vi.json')
OUTPUT_GLOSSARY_PATH = Path('scripts/write_essay_support/academic_collocation_glossary.json')

# 1. Curated Vietnamese Academic Translations for Polysemous / Mistranslated Terms
VIETNAMESE_CURATED: Dict[str, str] = {
    "abstract concept": "khái niệm trừu tượng",
    "academic achievement": "thành tích học tập, nghiên cứu",
    "academic career": "sự nghiệp học thuật / giảng dạy đại học",
    "academic circles": "giới học thuật / cộng đồng nghiên cứu",
    "academic community": "cộng đồng học thuật / giới nghiên cứu",
    "academic discipline": "ngành học / chuyên ngành học thuật",
    "academic discourse": "diễn ngôn học thuật / thảo luận chuyên môn",
    "academic institution": "cơ sở giáo dục / viện nghiên cứu học thuật",
    "academic life": "đời sống học thuật / môi trường đại học",
    "academic performance": "kết quả học tập / thành tích học thuật",
    "academic research": "nghiên cứu học thuật chuyên sâu",
    "academic skills": "kỹ năng học thuật / nghiên cứu",
    "academic study": "công trình nghiên cứu học thuật",
    "academic success": "sự thành công trong học tập và nghiên cứu",
    "academic work": "công trình / hoạt động học thuật",
    "academic world": "giới học thuật / môi trường hàn lâm",
    "academic writing": "văn phong / bài viết học thuật",
    "accept responsibility": "nhận trách nhiệm về hành động của mình",
    "acceptable behaviour": "hành vi chuẩn mực, được chấp nhận",
    "accurate assessment": "sự đánh giá chính xác, khách quan",
    "accurate description": "sự miêu tả chuẩn xác, đúng thực tế",
    "accurate information": "thông tin chính xác, đáng tin cậy",
    "accurate measurement": "phép đo lường chính xác",
    "achieve goal": "đạt được mục tiêu đã đề ra",
    "achieve objective": "hoàn thành mục tiêu cụ thể",
    "achieve outcome": "đạt được kết quả mong muốn",
    "acquire knowledge": "tiếp thu và tích lũy tri thức",
    "active involvement": "sự tham gia tích cực, chủ động",
    "active participant": "người tham gia tích cực, chủ động",
    "active participation": "sự tham gia chủ động, nhiệt tình",
    "active role": "vai trò tích cực, chủ động",
    "actively involved": "chủ động tham gia tích cực",
    "acutely aware": "nhận thức sâu sắc, rõ ràng",
    "add information": "bổ sung thêm thông tin cần thiết",
    "additional cost": "chi phí phát sinh thêm",
    "additional information": "thông tin bổ sung làm rõ",
    "additional problem": "vấn đề phát sinh thêm",
    "additional resources": "nguồn lực / tài nguyên bổ sung",
    "additional support": "sự hỗ trợ bổ sung",
    "administrative practices": "thông lệ / phương pháp quản lý hành chính",
    "adopt procedure": "áp dụng quy trình / thủ tục mới",
    "advanced economy": "nền kinh tế phát triển tiên tiến",
    "advanced technology": "công nghệ tiên tiến, hiện đại",
    "adverse reaction": "phản ứng bất lợi / tác dụng phụ",
    "affect development": "ảnh hưởng đến tiến trình phát triển",
    "affect outcome": "tác động trực tiếp đến kết quả cuối cùng",
    "allocate resources": "phân bổ nguồn lực hợp lý",
    "allow access": "cho phép tiếp cận / cấp quyền truy cập",
    "alternative approach": "cách tiếp cận thay thế, mới mẻ",
    "alternative explanation": "cách giải thích thay thế hợp lý",
    "alternative form": "hình thức thay thế",
    "alternative interpretation": "cách diễn giải khác / cách hiểu thay thế",
    "alternative method": "phương pháp thay thế khả thi",
    "alternative solution": "giải pháp thay thế tối ưu",
    "alternative source": "nguồn thay thế đáng tin cậy",
    "alternative view": "quan điểm khác biệt / góc nhìn đối lập",
    "ample evidence": "bằng chứng dồi dào, xác thực",
    "annual meeting": "cuộc họp thường niên định kỳ",
    "annual report": "báo cáo tổng kết thường niên",
    "annual review": "đánh giá tổng kết hàng năm",
    "apply equally": "áp dụng bình đẳng như nhau cho mọi trường hợp",
    "apply method": "áp dụng phương pháp nghiên cứu vào thực tế",
    "appropriate action": "hành động phù hợp, kịp thời",
    "appropriate behaviour": "hành vi ứng xử đúng mực",
    "appropriate data": "dữ liệu phù hợp, có giá trị",
    "appropriate language": "ngôn ngữ phù hợp với ngữ cảnh",
    "appropriate skills": "kỹ năng phù hợp với yêu cầu",
    "appropriate treatment": "phương pháp điều trị / cách đối xử phù hợp",
    "armed conflict": "xung đột vũ trang / chiến tranh cục bộ",
    "artificial intelligence": "trí tuệ nhân tạo",
    "assess impact": "đánh giá mức độ tác động",
    "assessment process": "quy trình đánh giá năng lực",
    "associated factors": "các yếu tố liên quan mật thiết",
    "assume responsibility": "gánh vác trách nhiệm",
    "assume role": "đảm nhận vai trò, trọng trách",
    "atomic energy": "năng lượng nguyên tử",
    "available data": "dữ liệu sẵn có để nghiên cứu",
    "available evidence": "bằng chứng hiện có",
    "available information": "thông tin hiện có",
    "available resources": "nguồn lực sẵn có để sử dụng",
    "average score": "điểm số trung bình",
    "background knowledge": "kiến thức nền tảng cần thiết",
    "basic assumption": "giả định cơ bản ban đầu",
    "basic component": "thành phần cốt lõi cơ bản",
    "basic concept": "khái niệm nền tảng cơ bản",
    "basic function": "chức năng cơ bản cốt yếu",
    "basic research": "nghiên cứu cơ bản",
    "basic structure": "cấu trúc nền tảng cơ bản",
    "become apparent": "trở nên rõ ràng, dễ thấy",
    "become evident": "hiển hiện rõ ràng qua chứng cứ",
    "become focus": "trở thành trọng tâm chú ý",
    "become independent": "trở nên độc lập, tự chủ",
    "become involved": "tham gia, can dự vào hoạt động",
    "become widespread": "trở nên phổ biến rộng rãi",
    "begin process": "bắt đầu quy trình thực hiện",
    "behave differently": "ứng xử, thể hiện khác biệt",
    "beneficial effect": "tác động có lợi, tích cực",
    "binary system": "hệ thống nhị phân / phân loại đúng sai cứng nhắc",
    "biological science": "khoa học sinh học / sinh vật học",
    "brief account": "bản tường thuật / bản tóm lược ngắn gọn",
    "brief discussion": "thảo luận ngắn gọn, súc tích",
    "brief history": "tóm tắt sơ lược lịch sử",
    "brief overview": "cái nhìn tổng quan ngắn gọn",
    "brief period": "khoảng thời gian ngắn",
    "brief review": "đánh giá ngắn gọn, cô đọng",
    "brief time": "khoảng thời gian ngắn ngủi",
    "briefly discuss": "thảo luận sơ lược, ngắn gọn",
    "broad agreement": "sự đồng thuận rộng rãi",
    "broad category": "nhóm phân loại rộng",
    "broad definition": "định nghĩa khái quát, rộng mở",
    "broad range": "phạm vi rộng lớn, đa dạng",
    "broader context": "bối cảnh rộng lớn hơn",
    "business sector": "khu vực doanh nghiệp / kinh tế tư nhân",
    "business transaction": "giao dịch kinh doanh, thương mại",
    "capitalist economy": "nền kinh tế tư bản chủ nghĩa",
    "capitalist society": "xã hội tư bản chủ nghĩa",
    "capitalist system": "hệ thống kinh tế tư bản",
    "capitalist world": "thế giới các nước tư bản",
    "career development": "phát triển sự nghiệp lâu dài",
    "career opportunity": "cơ hội phát triển nghề nghiệp",
    "careful analysis": "phân tích cẩn trọng, tỉ mỉ",
    "careful attention": "sự chú ý cẩn trọng, chu đáo",
    "careful consideration": "sự cân nhắc kỹ lưỡng, thận trọng",
    "carefully controlled": "được kiểm soát chặt chẽ, thận trọng",
    "carry out research": "tiến hành nghiên cứu khoa học",
    "carry out task": "thực hiện nhiệm vụ được giao",
    "causal relationship": "mối quan hệ nhân quả",
    "cause consequences": "dẫn tới những hậu quả nghiêm trọng",
    "cause stress": "gây ra căng thẳng, áp lực",
    "central characteristics": "những đặc điểm cốt lõi",
    "central control": "sự kiểm soát tập trung từ trung ương",
    "central focus": "trọng tâm cốt lõi của vấn đề",
    "central government": "chính phủ trung ương",
    "central problem": "vấn đề nan giải trọng tâm",
    "central role": "vai trò trung tâm / then chốt",
    "change attitude": "thay đổi thái độ, góc nhìn",
    "change constantly": "thay đổi liên tục, không ngừng",
    "change dramatically": "thay đổi sâu sắc, rõ rệt",
    "changing attitudes": "sự chuyển biến trong thái độ của xã hội",
    "changing nature": "bản chất luôn biến đổi",
    "changing needs": "nhu cầu không ngừng thay đổi",
    "changing world": "thế giới biến chuyển không ngừng",
    "characteristic feature": "đặc điểm đặc trưng tiêu biểu",
    "chemical reaction": "phản ứng hóa học",
    "civil society": "xã hội dân sự",
    "class consciousness": "ý thức giai cấp",
    "classic example": "ví dụ kinh điển, điển hình",
    "classic study": "nghiên cứu kinh điển, mẫu mực",
    "classic work": "tác phẩm kinh điển có giá trị lâu dài",
    "clear boundary": "ranh giới phân định rõ ràng",
    "clear distinction": "sự phân biệt rạch ròi, minh bạch",
    "clear evidence": "bằng chứng rõ ràng, xác thực",
    "clear focus": "định hướng / trọng tâm rõ ràng",
    "clear relationship": "mối quan hệ rõ ràng, minh bạch",
    "clear structure": "cấu trúc bài viết mạch lạc, rõ ràng",
    "clearly defined": "được định nghĩa rõ ràng, chính xác",
    "clearly demonstrated": "được chứng minh rõ ràng qua dữ liệu",
    "clearly evident": "rõ ràng, hiển nhiên trước mắt",
    "clearly important": "rõ ràng đóng vai trò quan trọng",
    "clearly understand": "hiểu thấu đáo, rõ ràng",
    "climate change": "biến đổi khí hậu toàn cầu",
    "close proximity": "khoảng cách rất gần về không gian",
    "close relationship": "mối quan hệ gắn bó, chặt chẽ",
    "close scrutiny": "sự xem xét / giám sát kỹ lưỡng",
    "closely connected": "gắn kết chặt chẽ với nhau",
    "closer examination": "sự xem xét / khảo sát kỹ lưỡng hơn",
    "cognitive ability": "khả năng nhận thức và xử lý thông tin",
    "cognitive development": "sự phát triển năng lực nhận thức",
    "cognitive skills": "kỹ năng nhận thức và tư duy",
    "collaborative learning": "học tập hợp tác nhóm",
    "collect data": "thu thập dữ liệu thực nghiệm",
    "collective identity": "bản sắc chung của tập thể",
    "collective memory": "ký ức tập thể của cộng đồng",
    "combined effect": "tác động tổng hợp / hiệu ứng cộng hưởng",
    "come into conflict": "nảy sinh xung đột, bất đồng",
    "commercial activity": "hoạt động thương mại",
    "commercial transaction": "giao dịch thương mại, mua bán",
    "commit crime": "hành vi phạm tội",
    "commit offence": "vi phạm pháp luật / quy định",
    "common characteristic": "đặc điểm chung phổ biến",
    "common culture": "văn hóa chung của cộng đồng",
    "common feature": "đặc điểm chung dễ nhận thấy",
    "common goal": "mục tiêu phấn đấu chung",
    "commonly accepted": "được chấp nhận rộng rãi trong xã hội",
    "commonly called": "thường được gọi là",
    "communicate effectively": "giao tiếp hiệu quả, truyền cảm",
    "comparative research": "nghiên cứu so sánh đối chiếu",
    "compelling argument": "lập luận thuyết phục, đanh thép",
    "compelling evidence": "bằng chứng xác thực, đầy sức thuyết phục",
    "compelling reason": "lý do thuyết phục, xác đáng",
    "competitive market": "thị trường cạnh tranh khốc liệt",
    "competitive pressure": "áp lực cạnh tranh gay gắt",
    "complex area": "lĩnh vực phức tạp, đa chiều",
    "complex interaction": "sự tương tác phức tạp qua lại",
    "complex issue": "vấn đề phức tạp, khó giải quyết",
    "complex pattern": "mô hình diễn biến phức tạp",
    "complex process": "quy trình phức tạp nhiều bước",
    "complex structure": "cấu trúc phức tạp đa tầng",
    "complex system": "hệ thống phức tạp nhiều mắt xích",
    "comprehensive account": "bản báo cáo / tường thuật toàn diện",
    "comprehensive approach": "cách tiếp cận toàn diện mọi mặt",
    "comprehensive overview": "cái nhìn tổng quan toàn diện",
    "comprehensive review": "bài tổng quan / đánh giá toàn diện",
    "comprehensive system": "hệ thống toàn diện, đồng bộ",
    "conceptual framework": "khung lý thuyết / khung khái niệm",
    "concerted effort": "nỗ lực phối hợp chung",
    "concluding probability": "xác suất suy đoán cuối cùng",
    "concluding remarks": "lời phát biểu / nhận định kết luận",
    "conduct analysis": "tiến hành phân tích số liệu",
    "conduct interview": "thực hiện phỏng vấn thu thập thông tin",
    "conduct research": "tiến hành nghiên cứu khoa học",
    "conduct study": "thực hiện công trình nghiên cứu",
    "conflict resolution": "giải quyết xung đột, tranh chấp",
    "conflicting interests": "các lợi ích xung đột, mâu thuẫn",
    "consider appropriate": "cân nhắc mức độ phù hợp",
    "consider impact": "cân nhắc các tác động tiềm tàng",
    "consider role": "xem xét vai trò cụ thể",
    "considerable attention": "sự quan tâm, chú ý đáng kể",
    "considerable degree": "mức độ đáng kể, rõ rệt",
    "considerable effort": "nỗ lực to lớn, đáng ghi nhận",
    "considerable influence": "sức ảnh hưởng đáng kể",
    "considerable interest": "sự quan tâm / chú ý sâu sắc",
    "considerable support": "sự ủng hộ, hỗ trợ to lớn",
    "consistent pattern": "khuynh hướng / mô hình nhất quán",
    "consistent results": "kết quả nhất quán qua các lần kiểm tra",
    "constant rate": "tỷ lệ duy trì ổn định không đổi",
    "constituent parts": "các bộ phận cấu thành nên tổng thể",
    "contemporary debate": "tranh luận đương đại sôi nổi",
    "contemporary issue": "vấn đề mang tính thời sự đương đại",
    "contemporary life": "nhịp sống đương đại hôm nay",
    "contemporary society": "xã hội đương đại ngày nay",
    "contextual factors": "các yếu tố thuộc về bối cảnh",
    "continued growth": "sự tăng trưởng liên tục, bền bỉ",
    "continuous process": "quá trình liên tục, không ngắt quãng",
    "contribute significantly": "đóng góp đáng kể vào thành công",
    "contribute to development": "đóng góp tích cực vào sự phát triển",
    "convey information": "truyền tải thông tin chính xác",
    "convey meaning": "truyền tải ý nghĩa sâu sắc",
    "convey message": "truyền tải thông điệp nhân văn",
    "coping strategy": "chiến lược thích ứng, giải tỏa áp lực",
    "core skills": "các kỹ năng cốt lõi nền tảng",
    "cover range": "bao quát phạm vi nhiều lĩnh vực",
    "cover topic": "bao quát và làm rõ chủ đề",
    "create conditions": "tạo điều kiện thuận lợi",
    "create environment": "xây dựng môi trường lý tưởng",
    "create impression": "tạo ấn tượng sâu sắc ban đầu",
    "create opportunities": "tạo ra nhiều cơ hội phát triển",
    "create opportunity": "tạo cơ hội thuận lợi",
    "create problems": "làm phát sinh rắc rối, trở ngại",
    "creative process": "tiến trình sáng tạo nghệ thuật",
    "creative thinking": "tư duy sáng tạo, đột phá",
    "creative work": "công trình / tác phẩm sáng tạo",
    "critical analysis": "phân tích phản biện sắc sảo",
    "critical approach": "cách tiếp cận phản biện khoa học",
    "critical attention": "sự nghiên cứu, mổ xẻ kỹ lưỡng",
    "critical essay": "bài tiểu luận phê bình, phản biện",
    "critical factor": "yếu tố then chốt quyết định",
    "critical inquiry": "sự tìm tòi, tra vấn phản biện",
    "critical perspective": "góc nhìn phê phán, phản biện khách quan",
    "critical reflection": "sự suy ngẫm, tự soi chiếu phản biện",
    "critical scrutiny": "sự xem xét, thẩm định khắt khe",
    "critical thinking": "tư duy phản biện độc lập",
    "critical writing": "lối viết phản biện sắc bén",
    "crucial difference": "sự khác biệt mang tính quyết định",
    "crucial factor": "yếu tố mang tính then chốt",
    "crucial importance": "tầm quan trọng sống còn, cốt yếu",
    "crucial part": "phần thiết yếu không thể tách rời",
    "cultural activity": "hoạt động văn hóa truyền thống",
    "cultural aspect": "khía cạnh văn hóa đặc thù",
    "cultural attitudes": "thái độ và quan niệm văn hóa",
    "cultural background": "nền tảng văn hóa xuất thân",
    "cultural context": "bối cảnh văn hóa xã hội",
    "cultural diversity": "sự đa dạng bản sắc văn hóa",
    "cultural heritage": "di sản văn hóa quý báu",
    "cultural history": "tiến trình lịch sử văn hóa",
    "cultural identity": "bản sắc văn hóa dân tộc",
    "cultural influence": "ảnh hưởng văn hóa sâu rộng",
    "cultural life": "đời sống văn hóa tinh thần",
    "cultural perspective": "góc nhìn dựa trên bản sắc văn hóa",
    "cultural practice": "tập tục, phong tục văn hóa",
    "cultural values": "các giá trị văn hóa cốt lõi",
    "current climate": "bối cảnh / bầu không khí xã hội hiện nay",
    "current status": "tình trạng hiện tại của sự việc",
    "current technology": "công nghệ hiện hành đang áp dụng",
    "daily living": "sinh hoạt thường nhật hàng ngày",
    "data gathering": "quá trình thu thập số liệu",
    "deep understanding": "sự thấu hiểu sâu sắc bản chất",
    "defining characteristic": "đặc trưng cốt lõi giúp định danh",
    "deliberate attempt": "nỗ lực có chủ đích rõ ràng",
    "democratic society": "xã hội dân chủ, văn minh",
    "demographic change": "sự biến động nhân khẩu học",
    "demographic characteristics": "đặc điểm nhân khẩu học",
    "demographic factor": "yếu tố biến đổi nhân khẩu học",
    "demonstrate competence": "thể hiện năng lực chuyên môn",
    "deny access": "từ chối quyền tiếp cận, sử dụng",
    "dependent variable": "biến số phụ thuộc trong thí nghiệm",
    "describe procedure": "mô tả quy trình thực hiện cụ thể",
    "desired outcome": "kết quả mong đợi cuối cùng",
    "developmental process": "tiến trình phát triển tự nhiên",
    "diagnostic test": "bài kiểm tra chẩn đoán năng lực",
    "differ significantly": "khác biệt rõ rệt về bản chất",
    "digital information": "thông tin kỹ thuật số",
    "digital media": "truyền thông kỹ thuật số hiện đại",
    "digital technology": "công nghệ số tiên tiến",
    "direct access": "quyền tiếp cận trực tiếp không qua trung gian",
    "direct communication": "giao tiếp trực tiếp đối thoại",
    "direct consequences": "hệ quả trực tiếp nhãn tiền",
    "direct impact": "tác động trực tiếp ngay tức thì",
    "directly connected": "kết nối trực tiếp với nhau",
    "directly responsible": "chịu trách nhiệm trực tiếp",
    "discuss issue": "thảo luận chuyên sâu về vấn đề",
    "discuss topic": "thảo luận xoay quanh chủ đề",
    "disposable income": "thu nhập khả dụng sau thuế",
    "distinct group": "nhóm đối tượng riêng biệt",
    "diverse background": "hoàn cảnh xuất thân đa dạng",
    "diverse group": "tập hợp nhóm người đa dạng",
    "diverse range": "phạm vi phong phú, đa dạng",
    "documentary evidence": "chứng cứ trên tài liệu, văn bản",
    "domestic market": "thị trường nội địa trong nước",
    "domestic sphere": "phạm vi gia đình / đời sống nội bộ",
    "domestic violence": "nạn bạo lực gia đình",
    "dominant culture": "văn hóa chủ đạo chiếm ưu thế",
    "dominant discourse": "luồng quan điểm chi phối xã hội",
    "dominant group": "nhóm có vị thế chi phối",
    "draw attention": "thu hút sự chú ý của dư luận",
    "driving force": "động lực chính thúc đẩy phát triển",
    "dynamic equilibrium": "trạng thái cân bằng động",
    "dynamic nature": "bản chất năng động, luôn biến chuyển",
    "earlier discussion": "cuộc thảo luận đã nêu ở phần trước",
    "earlier times": "thời kỳ trước đây trong lịch sử",
    "easily accessible": "dễ dàng tiếp cận và sử dụng",
    "easily identified": "dễ dàng nhận biết, xác định",
    "easy access": "khả năng tiếp cận thuận tiện",
    "economic activity": "hoạt động kinh tế sôi nổi",
    "economic affairs": "các vấn đề kinh tế xã hội",
    "economic analysis": "phân tích kinh tế chuyên sâu",
    "economic benefits": "lợi ích kinh tế thiết thực",
    "economic consequences": "hệ quả kinh tế lâu dài",
    "economic context": "bối cảnh kinh tế vĩ mô",
    "economic forces": "các động lực kinh tế chi phối",
    "economic goal": "mục tiêu kinh tế trọng tâm",
    "economic growth": "sự tăng trưởng kinh tế vững chắc",
    "economic inequality": "sự bất bình đẳng về kinh tế",
    "economic integration": "tiến trình hội nhập kinh tế",
    "economic interests": "lợi ích kinh tế cốt lõi",
    "economic power": "tiềm lực và sức mạnh kinh tế",
    "economic prosperity": "sự thịnh vượng về kinh tế",
    "economic relationships": "các mối quan hệ kinh tế song phương",
    "economic resources": "nguồn lực kinh tế dồi dào",
    "economic sector": "khu vực kinh tế trọng điểm",
    "economic stability": "sự ổn định của nền kinh tế",
    "economic status": "vị thế kinh tế trong xã hội",
    "economic structure": "cơ cấu nền kinh tế",
    "economic success": "thành công rực rỡ về kinh tế",
    "economic welfare": "phúc lợi kinh tế của người dân",
    "educational institution": "cơ sở giáo dục / trường học",
    "educational opportunity": "cơ hội học tập rộng mở",
    "educational policy": "chính sách đổi mới giáo dục",
    "educational programme": "chương trình đào tạo giáo dục",
    "educational qualification": "văn bằng / trình độ học vấn",
    "effective communication": "giao tiếp hiệu quả, thuyết phục",
    "effective implementation": "triển khai thực thi hiệu quả",
    "effective intervention": "sự can thiệp kịp thời và hiệu quả",
    "effective management": "công tác quản lý hiệu quả",
    "effective participation": "sự tham gia mang lại hiệu quả thực chất",
    "electronic access": "tiếp cận thông tin qua môi trường mạng",
    "electronic communication": "giao tiếp qua phương tiện điện tử",
    "electronic media": "phương tiện truyền thông điện tử",
    "electronic resources": "nguồn học liệu điện tử phong phú",
    "emotional impact": "tác động mạnh mẽ đến cảm xúc",
    "emotional intelligence": "trí tuệ cảm xúc (EQ)",
    "emotional reaction": "phản ứng cảm xúc bột phát",
    "emotional response": "sự hồi đáp về mặt cảm xúc",
    "emotional support": "sự chia sẻ, nâng đỡ tinh thần",
    "empirical investigation": "cuộc điều tra thực nghiệm thực tế",
    "empirical support": "bằng chứng thực nghiệm củng cố lý thuyết",
    "employment opportunities": "cơ hội việc làm rộng mở",
    "encounter difficulties": "gặp phải những khó khăn thử thách",
    "encounter problems": "đối mặt với những sự cố phát sinh",
    "encourage development": "khuyến khích sự phát triển sáng tạo",
    "engage in activity": "tích cực tham gia vào hoạt động",
    "enhance learning": "nâng cao chất lượng học tập",
    "enhance performance": "nâng cao hiệu suất làm việc",
    "entire range": "toàn bộ dải quang phổ / phổ rộng",
    "entirely clear": "hoàn toàn sáng tỏ, không mơ hồ",
    "entirely different": "hoàn toàn khác biệt về bản chất",
    "environmental changes": "những biến đổi của môi trường",
    "environmental concern": "mối quan ngại sâu sắc về môi trường",
    "environmental consequences": "hậu quả môi trường nặng nề",
    "environmental damage": "tổn hại nghiêm trọng đến môi trường",
    "environmental degradation": "sự suy thoái môi trường sinh thái",
    "environmental impact": "tác động môi trường trên diện rộng",
    "environmental pollution": "nạn ô nhiễm môi trường sống",
    "environmental protection": "bảo vệ môi trường thiên nhiên",
    "equal status": "địa vị bình đẳng trong xã hội",
    "equally important": "quan trọng tương đương nhau",
    "essential component": "thành phần thiết yếu không thể thiếu",
    "essential element": "yếu tố cốt lõi mang tính quyết định",
    "essential feature": "đặc điểm thiết yếu đặc trưng",
    "essential function": "chức năng cốt yếu phục vụ mục tiêu",
    "established practice": "thông lệ lâu đời / tập quán đã định hình",
    "ethical consideration": "sự cân nhắc về mặt đạo đức",
    "ethical dilemma": "tình huống nan giải về mặt đạo đức",
    "ethical issue": "vấn đề liên quan đến chuẩn mực đạo đức",
    "ethical principle": "nguyên tắc đạo đức cốt lõi",
    "ethnic community": "cộng đồng người dân tộc",
    "ethnic diversity": "sự đa dạng về thành phần sắc tộc",
    "ethnic group": "nhóm sắc tộc / dân tộc thiểu số",
    "ethnic identity": "bản sắc văn hóa của dân tộc",
    "exercise authority": "thực thi quyền hạn / thẩm quyền hợp pháp",
    "expand rapidly": "mở rộng quy mô nhanh chóng",
    "experience difficulties": "trải qua những giai đoạn khó khăn",
    "experience problems": "gặp phải các vướng mắc trở ngại",
    "experiential learning": "học tập qua trải nghiệm thực tế",
    "experimental design": "thiết kế quy trình thực nghiệm",
    "experimental results": "kết quả thí nghiệm thực nghiệm",
    "explanatory power": "khả năng / giá trị giải thích của lý thuyết",
    "explore further": "tìm hiểu và đào sâu nghiên cứu thêm",
    "explore issue": "khảo sát toàn diện về vấn đề",
    "external forces": "các thế lực tác động từ bên ngoài",
    "external threat": "mối đe dọa tiềm ẩn từ bên ngoài",
    "extract data": "trích xuất và chọn lọc dữ liệu",
    "extract information": "chắt lọc thông tin hữu ích",
    "extremely powerful": "vô cùng mạnh mẽ và hiệu lực",
    "extremely useful": "cực kỳ hữu ích trong thực tế",
    "extremely valuable": "vô cùng quý giá và đáng trân trọng",
    "face challenge": "đối mặt với thách thức to lớn",
    "face difficulties": "đối diện với muôn vàn khó khăn",
    "face dilemma": "đứng trước tình thế tiến thoái lưỡng nan",
    "face discrimination": "đối mặt với nạn phân biệt đối xử",
    "facial expression": "biểu cảm qua nét mặt",
    "facilitate development": "tạo điều kiện thuận lợi cho sự phát triển",
    "fair treatment": "sự đối xử công bằng, văn minh",
    "fairly clear": "tương đối rõ ràng, dễ hiểu",
    "fairly common": "khá phổ biến trong đời sống",
    "federal government": "chính phủ liên bang",
    "final decision": "quyết định mang tính chung cuộc",
    "final outcome": "kết quả chung cuộc cuối cùng",
    "final product": "thành phẩm cuối cùng hoàn chỉnh",
    "final result": "kết quả cuối cùng đạt được",
    "financial affairs": "các vấn đề quản lý tài chính",
    "financial assistance": "hỗ trợ tài chính kịp thời",
    "financial institution": "tổ chức / định chế tài chính",
    "financial management": "công tác quản lý tài chính",
    "financial market": "thị trường tài chính sôi động",
    "find evidence": "tìm kiếm chứng cứ xác thực",
    "find information": "tìm kiếm dữ liệu thông tin",
    "finite number": "số lượng hữu hạn có thể đếm được",
    "flexible approach": "cách tiếp cận linh hoạt, tùy biến",
    "focus attention": "tập trung cao độ sự chú ý",
    "follow instructions": "tuân thủ nghiêm ngặt chỉ dẫn",
    "follow procedure": "thực hiện đúng quy trình thủ tục",
    "foreign currency": "ngoại tệ dự trữ",
    "foster self-efficacy": "nuôi dưỡng niềm tin vào năng lực bản thân",
    "free access": "quyền tự do tiếp cận không giới hạn",
    "free movement": "quyền tự do đi lại / lưu thông tự do",
    "freely available": "được cung cấp miễn phí rộng rãi",
    "fulfil obligation": "hoàn thành trọn vẹn nghĩa vụ",
    "full employment": "trạng thái toàn dụng việc làm",
    "full participation": "sự tham gia đầy đủ của các bên",
    "full potential": "phát huy trọn vẹn tiềm năng",
    "fully informed": "được cung cấp đầy đủ thông tin",
    "functional requirement": "yêu cầu chức năng của hệ thống",
    "fundamental aspect": "khía cạnh nền tảng cơ bản",
    "fundamental assumption": "giả định nền tảng ban đầu",
    "fundamental change": "sự thay đổi mang tính căn bản",
    "fundamentally different": "khác biệt một cách căn bản",
    "further explanation": "lời giải thích tường minh hơn",
    "future prospects": "triển vọng xán lạn trong tương lai",
    "gender equality": "bình đẳng giới thực chất",
    "geographic distribution": "sự phân bố theo không gian địa lý",
    "give access": "cấp quyền tiếp cận hệ thống",
    "give consent": "chấp thuận / đưa ra sự đồng thuận",
    "give consideration": "xem xét / cân nhắc kỹ lưỡng",
    "give emphasis": "nhấn mạnh / đặt trọng tâm vào",
    "give explanation": "đưa ra lời giải thích thuyết phục",
    "give feedback": "đưa ra phản hồi mang tính xây dựng",
    "give guidance": "đưa ra lời khuyên chỉ dẫn tận tình",
    "global capitalism": "chủ nghĩa tư bản toàn cầu",
    "global context": "bối cảnh toàn cầu hóa",
    "global culture": "văn hóa mang tầm ảnh hưởng toàn cầu",
    "global economy": "nền kinh tế toàn cầu gắn kết",
    "global marketplace": "thị trường thương mại toàn cầu",
    "global media": "mạng lưới truyền thông toàn cầu",
    "global perspective": "tầm nhìn / góc nhìn toàn cầu",
    "global trade": "thương mại quốc tế toàn cầu",
    "global village": "ngôi làng toàn cầu kết nối",
    "governing body": "cơ quan quản trị / điều hành",
    "government control": "sự kiểm soát của chính phủ",
    "government department": "cơ quan / bộ phận trực thuộc chính phủ",
    "government expenditure": "ngân sách chi tiêu của chính phủ",
    "graphical representation": "biểu diễn trực quan bằng đồ họa",
    "great diversity": "sự đa dạng phong phú to lớn",
    "great majority": "đại đa số áp đảo",
    "great potential": "tiềm năng phát triển to lớn",
    "greater autonomy": "quyền tự chủ lớn hơn cho cá nhân",
    "greater awareness": "nhận thức xã hội được nâng cao",
    "greater equality": "sự công bằng lớn hơn cho mọi người",
    "greater flexibility": "tính linh hoạt cao hơn trong hành động",
    "greatly enhance": "nâng cao và cải thiện đáng kể",
    "greatly reduced": "được giảm thiểu một cách đáng kể",
    "growing awareness": "nhận thức ngày càng gia tăng",
    "have limitations": "bộc lộ những điểm hạn chế nhất định",
    "have obligation": "có nghĩa vụ và trách nhiệm pháp lý",
    "have potential": "sở hữu tiềm năng phát triển",
    "high concentration": "mức độ tập trung mật độ cao",
    "high expectations": "kỳ vọng lớn lao vào thành tích",
    "high incidence": "tỷ lệ xuất hiện / mắc bệnh cao",
    "high probability": "xác suất xảy ra rất cao",
    "high score": "điểm số xuất sắc vượt trội",
    "high status": "vị thế xã hội cao, được trọng vọng",
    "high unemployment": "tỷ lệ thất nghiệp ở mức cao",
    "highly dependent": "phụ thuộc nặng nề vào đối tượng khác",
    "highly efficient": "đạt hiệu suất làm việc rất cao",
    "highly significant": "có ý nghĩa khoa học và thực tiễn rất cao",
    "highly skilled": "tay nghề cao, trình độ chuyên môn tốt",
    "highly sophisticated": "cực kỳ tinh vi, phức tạp và hiện đại",
    "highly successful": "gặt hái thành công vang dội",
    "historical account": "tài liệu / ghi chép lịch sử chân thực",
    "historical context": "bối cảnh lịch sử của thời đại",
    "historical knowledge": "tri thức lịch sử quý giá",
    "historical perspective": "góc nhìn thấu suốt qua lăng kính lịch sử",
    "historical writing": "tác phẩm sử học / công trình nghiên cứu lịch sử",
    "holistic approach": "cách tiếp cận toàn diện, đa chiều",
    "human activity": "hoạt động của con người tác động lên tự nhiên",
    "human behaviour": "hành vi ứng xử của con người",
    "human interaction": "sự tương tác xã hội giữa con người",
    "human society": "xã hội loài người văn minh",
    "human species": "loài người trong sinh giới",
    "ideally suited": "hoàn toàn phù hợp / lựa chọn lý tưởng nhất",
    "immediate environment": "môi trường xung quanh / trực tiếp",
    "immediately apparent": "hiển hiện rõ ràng ngay trước mắt",
    "immediately following": "ngay tiếp sau / diễn ra liền sau",
    "imported goods": "hàng hóa nhập khẩu từ nước ngoài",
    "imported products": "sản phẩm ngoại nhập chất lượng",
    "impose constraints": "áp đặt những rào cản hạn chế",
    "impose limitations": "áp đặt các giới hạn nghiêm ngặt",
    "improved performance": "hiệu suất được cải thiện rõ rệt",
    "increase awareness": "nâng cao nhận thức của cộng đồng",
    "increased awareness": "nhận thức được nâng cao rõ rệt",
    "increased competition": "sự cạnh tranh ngày càng gay gắt",
    "increased demand": "nhu cầu tiêu dùng tăng cao",
    "increased pressure": "áp lực đè nặng ngày càng lớn",
    "increased productivity": "năng suất lao động được nâng cao",
    "increased risk": "nguy cơ rủi ro gia tăng",
    "increasing demand": "nhu cầu thị trường không ngừng gia tăng",
    "increasing pressure": "áp lực xã hội ngày càng gia tăng",
    "increasingly popular": "ngày càng được đón nhận và ưa chuộng",
    "increasingly sophisticated": "ngày càng trở nên tinh vi và hiện đại",
    "independent state": "nhà nước độc lập, có chủ quyền",
    "indigenous people": "người dân bản địa địa phương",
    "indigenous population": "quần thể dân cư bản địa",
    "individual behaviour": "hành vi ứng xử của từng cá nhân",
    "individual case": "từng trường hợp cụ thể, cá biệt",
    "individual characteristics": "nét đặc trưng riêng của mỗi cá nhân",
    "individual choice": "sự lựa chọn tự do của cá nhân",
    "individual experience": "trải nghiệm thực tế của riêng mỗi người",
    "individual interests": "lợi ích riêng của từng cá nhân",
    "individual needs": "nhu cầu thiết thực của từng cá nhân",
    "individual responsibility": "trách nhiệm của mỗi cá nhân với cộng đồng",
    "industrial capitalism": "chủ nghĩa tư bản công nghiệp",
    "infinite number": "số lượng vô hạn, không cùng",
    "information sharing": "sự chia sẻ thông tin cởi mở",
    "informed consent": "sự đồng thuận trên cơ sở hiểu rõ thông tin",
    "institutional arrangement": "cơ chế / sắp xếp thể chế",
    "institutional context": "bối cảnh thuộc về thể chế",
    "institutional framework": "khung pháp lý và thể chế",
    "institutional structure": "cơ cấu tổ chức thể chế",
    "integral part": "phần không thể thiếu của tổng thể",
    "intellectual curiosity": "trí tò mò và niềm say mê khám phá tri thức",
    "intellectual property": "quyền sở hữu trí tuệ",
    "intellectual work": "hoạt động lao động trí óc",
    "interested party": "bên có quyền lợi liên quan / các bên hữu quan",
    "internal control": "công tác kiểm soát nội bộ",
    "internal organ": "cơ quan nội tạng trong cơ thể",
    "international body": "tổ chức quốc tế",
    "international community": "cộng đồng quốc tế các quốc gia",
    "interpersonal relationships": "mối quan hệ tương tác giữa các cá nhân",
    "interpersonal skills": "kỹ năng giao tiếp và ứng xử giữa người với người",
    "intimately connected": "gắn bó mật thiết, khăng khít",
    "intrinsic value": "giá trị nội tại vốn có",
    "irreversible physical trauma": "chấn thương thể chất không thể phục hồi",
    "key area": "lĩnh vực trọng tâm / then chốt",
    "key aspect": "khía cạnh trọng tâm cốt yếu",
    "key characteristic": "đặc điểm then chốt nổi bật",
    "key findings": "những phát hiện nghiên cứu then chốt",
    "large majority": "đại đa số / phần lớn áp đảo",
    "largely confined": "phần lớn bị giới hạn trong phạm vi hẹp",
    "largely responsible": "chịu phần lớn trách nhiệm",
    "learning activity": "hoạt động học tập tương tác",
    "learning process": "tiến trình học tập và tích lũy",
    "legal action": "hành động pháp lý khởi kiện",
    "legal basis": "cơ sở pháp lý vững chắc",
    "legal obligation": "nghĩa vụ tuân thủ theo luật định",
    "legal requirement": "yêu cầu bắt buộc của pháp luật",
    "liberal democracy": "nền dân chủ tự do tiến bộ",
    "lifelong learning": "tinh thần học tập suốt đời",
    "limited access": "sự tiếp cận bị hạn chế",
    "limited capacity": "quy mô / năng lực bị giới hạn",
    "literal sense": "hiểu theo đúng nghĩa đen của từ",
    "little impact": "tác động mờ nhạt, không đáng kể",
    "local area": "địa bàn khu vực địa phương",
    "local authority": "chính quyền địa phương sở tại",
    "local circumstances": "hoàn cảnh thực tế tại địa phương",
    "local community": "cộng đồng dân cư địa phương",
    "local culture": "văn hóa bản địa đặc trưng",
    "local economy": "kinh tế địa phương tự cường",
    "low income": "mức thu nhập thấp trong xã hội",
    "low unemployment": "tỷ lệ thất nghiệp ở mức thấp",
    "maintain contact": "duy trì liên lạc thường xuyên",
    "major advantage": "lợi thế nổi bật to lớn",
    "major area": "lĩnh vực chính / trọng tâm",
    "major cause": "nguyên nhân chính dẫn tới sự việc",
    "major challenge": "thử thách lớn cần vượt qua",
    "major reason": "lý do căn bản, chủ chốt",
    "make adjustments": "thực hiện điều chỉnh linh hoạt",
    "make arrangements": "chuẩn bị và sắp xếp chu đáo",
    "make assessment": "đưa ra sự đánh giá khách quan",
    "make prediction": "đưa ra dự đoán có căn cứ khoa học",
    "make transition": "thực hiện bước chuyển đổi chiến lược",
    "male dominance": "sự gia trưởng / áp đảo của nam giới",
    "manual worker": "lao động chân tay / công nhân phổ thông",
    "manufacturing sector": "khu vực ngành công nghiệp chế tạo",
    "markedly different": "khác biệt một cách rõ rệt",
    "mean score": "điểm số trung bình cộng",
    "media coverage": "sự đưa tin rộng rãi của truyền thông",
    "meet expectations": "đáp ứng kỳ vọng của mọi người",
    "mental health": "sức khỏe tinh thần của con người",
    "mental state": "trạng thái tâm lý tinh thần",
    "metropolitan area": "vùng đại đô thị phát triển",
    "middle management": "đội ngũ quản lý cấp trung",
    "military force": "lực lượng quân sự quốc gia",
    "military service": "nghĩa vụ quân sự vẻ vang",
    "modern culture": "nền văn hóa hiện đại văn minh",
    "modern method": "phương pháp hiện đại, tiên tiến",
    "modern society": "xã hội hiện đại ngày nay",
    "modern technology": "công nghệ hiện đại tối tân",
    "moral dilemma": "tình huống khó xử về mặt lương tâm",
    "municipal government": "chính quyền thành phố sở tại",
    "mutual recognition": "sự công nhận và tôn trọng lẫn nhau",
    "mutual support": "sự tương trợ, đùm bọc lẫn nhau",
    "mutual trust": "sự tin tưởng, tín nhiệm lẫn nhau",
    "mutual understanding": "sự thấu hiểu và sẻ chia lẫn nhau",
    "national identity": "bản sắc dân tộc độc đáo",
    "national language": "ngôn ngữ quốc gia chính thức",
    "national security": "an ninh quốc gia thiêng liêng",
    "natural conditions": "điều kiện tự nhiên của vùng miền",
    "natural disaster": "thiên tai khắc nghiệt",
    "natural environment": "môi trường sinh thái tự nhiên",
    "natural history": "lịch sử tự nhiên của trái đất",
    "natural resources": "nguồn tài nguyên thiên nhiên phong phú",
    "natural science": "các ngành khoa học tự nhiên",
    "negative aspect": "khía cạnh tiêu cực bất lợi",
    "negative attitude": "thái độ tiêu cực, bi quan",
    "negative effect": "tác động tiêu cực xấu đi",
    "negative feedback": "phản hồi tiêu cực cần khắc phục",
    "negative impact": "tác động tiêu cực gây tổn hại",
    "negatively correlated": "tương quan nghịch biến",
    "new initiative": "sáng kiến mới mang tính đột phá",
    "newly acquired": "mới đạt được / vừa mới sở hữu",
    "normal distribution": "phân phối chuẩn (trong lý thuyết xác suất)",
    "nuclear energy": "năng lượng hạt nhân nguyên tử",
    "nuclear family": "mô hình gia đình hạt nhân hai thế hệ",
    "numerous studies": "rất nhiều công trình nghiên cứu khoa học",
    "obtain result": "thu được kết quả cụ thể",
    "optimal solution": "giải pháp tối ưu nhất",
    "paramount importance": "tầm quan trọng tối thượng hàng đầu",
    "particularly evident": "đặc biệt rõ nét, dễ nhận thấy",
    "particularly significant": "đặc biệt có ý nghĩa to lớn",
    "particularly valuable": "đặc biệt có giá trị hữu ích",
    "partly responsible": "chịu một phần trách nhiệm",
    "perceived need": "nhu cầu được cảm nhận / nhìn nhận",
    "perceived threat": "mối đe dọa được cảm nhận",
    "personal choice": "sự lựa chọn tự do của cá nhân",
    "personal communication": "giao tiếp trao đổi riêng tư",
    "personal experience": "kinh nghiệm sống thực tế của bản thân",
    "personal interest": "sở thích và đam mê riêng của cá nhân",
    "personal knowledge": "vốn tri thức tích lũy của cá nhân",
    "personal responsibility": "trách nhiệm tự thân của mỗi người",
    "personal safety": "sự an toàn tính mạng của cá nhân",
    "personal space": "không gian riêng tư của cá nhân",
    "physical activity": "hoạt động thể chất, vận động cơ thể",
    "physical appearance": "diện mạo ngoại hình bên ngoài",
    "physical characteristics": "đặc điểm thể chất / tính chất vật lý",
    "physical contact": "tiếp xúc thể chất trực tiếp",
    "physical health": "sức khỏe thể chất tráng kiện",
    "physical proximity": "khoảng cách gần gũi về không gian",
    "physical space": "không gian vật lý thực tế",
    "pioneering work": "công trình nghiên cứu tiên phong",
    "pivotal role": "vai trò then chốt, xoay chuyển tình thế",
    "political instability": "sự bất ổn định về chính trị",
    "political participation": "sự tham gia vào đời sống chính trị",
    "political representation": "sự đại diện tiếng nói chính trị",
    "political stability": "sự ổn định chính trị vững vàng",
    "poorly understood": "chưa được thấu hiểu đầy đủ và cặn kẽ",
    "popular culture": "nền văn hóa đại chúng phổ biến",
    "popular media": "các phương tiện truyền thông đại chúng",
    "pose challenge": "đặt ra thử thách nan giải",
    "pose threat": "đặt ra mối đe dọa nghiêm trọng",
    "potential benefits": "những lợi ích tiềm năng to lớn",
    "potential risk": "những rủi ro tiềm ẩn nguy hiểm",
    "potentially dangerous": "tiềm ẩn nguy cơ nguy hiểm",
    "practical consideration": "sự cân nhắc về mặt thực tế",
    "practical difficulties": "những khó khăn phát sinh trong thực tế",
    "practical issue": "vấn đề thực tiễn cần giải quyết",
    "practical significance": "ý nghĩa thực tiễn to lớn",
    "predictive power": "khả năng dự báo chuẩn xác của mô hình",
    "present challenge": "đặt ra thử thách / thách thức lớn",
    "presidential election": "cuộc bầu cử tổng thống",
    "primary purpose": "mục đích chính yếu ban đầu",
    "prime time": "khung giờ vàng phát sóng truyền hình",
    "private individual": "cá nhân công dân bình thường",
    "private investment": "dòng vốn đầu tư tư nhân",
    "private sector": "khu vực kinh tế tư nhân năng động",
    "private sphere": "không gian đời tư cá nhân",
    "professional activity": "hoạt động chuyên môn nghiệp vụ",
    "professional body": "tổ chức / hiệp hội chuyên môn",
    "professional colleague": "đồng nghiệp trong ngành / cùng chuyên môn",
    "professional development": "phát triển kỹ năng nghề nghiệp chuyên môn",
    "professional staff": "đội ngũ nhân sự chuyên nghiệp",
    "professional training": "đào tạo nghiệp vụ chuyên môn",
    "profound effect": "ảnh hưởng sâu rộng lâu dài",
    "profound impact": "tác động sâu sắc đến nhận thức",
    "provide benefit": "mang lại lợi ích thiết thực",
    "provide foundation": "tạo dựng nền tảng vững chắc",
    "provide guidance": "cung cấp hướng dẫn, định hướng chu đáo",
    "provide material": "cung cấp tài liệu / tư liệu học tập",
    "provide service": "cung cấp dịch vụ chất lượng cao",
    "public access": "quyền tiếp cận công cộng của người dân",
    "public administration": "công tác quản lý hành chính công",
    "public attitudes": "thái độ và cách nhìn của công chúng",
    "public authority": "cơ quan công quyền thực thi pháp luật",
    "public discourse": "các cuộc thảo luận cởi mở nơi công cộng",
    "public expenditure": "chi tiêu ngân sách công của nhà nước",
    "public transport": "phương tiện giao thông công cộng",
    "public welfare": "phúc lợi công cộng cho toàn xã hội",
    "published material": "tài liệu đã được xuất bản chính thức",
    "push physiological boundaries": "vượt qua các giới hạn sinh lý của cơ thể",
    "readily accessible": "dễ dàng tiếp cận mà không gặp trở ngại",
    "reduce emissions": "cắt giảm lượng khí thải nhà kính",
    "reduce likelihood": "giảm thiểu nguy cơ xảy ra sự cố",
    "reduce stress": "giải tỏa căng thẳng và lo âu",
    "reflective practice": "thực hành tự soi chiếu / chiêm nghiệm bản thân",
    "reflective question": "câu hỏi gợi mở tư duy chiêm nghiệm",
    "regulatory framework": "khung khổ pháp lý và quy định",
    "relative autonomy": "quyền tự chủ tương đối trong hành động",
    "relatively constant": "duy trì ở mức tương đối ổn định",
    "relatively simple": "tương đối đơn giản và dễ thực hiện",
    "relatively stable": "tương đối ổn định qua thời gian",
    "religious freedom": "quyền tự do tín ngưỡng, tôn giáo",
    "remain constant": "duy trì không đổi qua thời gian",
    "remain stable": "giữ vững sự ổn định lâu dài",
    "renewable energy": "nguồn năng lượng sạch tái tạo",
    "representative government": "chính phủ đại diện cho ý chí của nhân dân",
    "research effort": "nỗ lực nghiên cứu khoa học bền bỉ",
    "risk assessment": "công tác đánh giá mức độ rủi ro",
    "rote memorization": "học vẹt máy móc, không hiểu sâu bản chất",
    "rural area": "khu vực nông thôn thanh bình",
    "rural community": "cộng đồng cư dân nông thôn",
    "rural economy": "nền kinh tế nông nghiệp nông thôn",
    "rural population": "dân cư sinh sống tại vùng nông thôn",
    "safe sex": "quan hệ tình dục an toàn",
    "scholarly journal": "tạp chí nghiên cứu học thuật uy tín",
    "scholarly literature": "tài liệu / các công trình nghiên cứu học thuật",
    "scholarly research": "nghiên cứu học thuật chuyên sâu",
    "scholarly work": "công trình nghiên cứu học thuật",
    "scientific discourse": "diễn ngôn / thảo luận khoa học nghiêm túc",
    "seek help": "chủ động tìm kiếm sự giúp đỡ",
    "senior management": "ban lãnh đạo cấp cao của tổ chức",
    "service sector": "khu vực ngành dịch vụ",
    "sexual orientation": "xu hướng tính dục tự nhiên",
    "share information": "chia sẻ thông tin một cách cởi mở",
    "short duration": "khoảng thời gian diễn ra ngắn ngủi",
    "short period": "khoảng thời gian ngắn",
    "significant growth": "sự tăng trưởng nhảy vọt đáng kể",
    "significant improvement": "sự cải thiện vượt bậc đáng ghi nhận",
    "significant interaction": "sự tương tác đáng kể qua lại",
    "simple majority": "đa số quá bán giản đơn",
    "skilled worker": "công nhân có tay nghề chuyên môn cao",
    "social activity": "hoạt động giao lưu xã hội",
    "social aspect": "khía cạnh đời sống xã hội",
    "social attitudes": "thái độ và định kiến của xã hội",
    "social background": "nền tảng xuất thân xã hội",
    "social democracy": "chủ nghĩa dân chủ xã hội",
    "social expectations": "kỳ vọng và chuẩn mực của xã hội",
    "social integration": "tiến trình hòa nhập xã hội",
    "social interaction": "sự giao tiếp và tương tác xã hội",
    "social isolation": "sự cô lập / xa lánh xã hội",
    "social mobility": "sự dịch chuyển địa vị xã hội",
    "social welfare": "chính sách phúc lợi xã hội toàn dân",
    "socially acceptable": "phù hợp với chuẩn mực chung của xã hội",
    "socioeconomic status": "vị thế kinh tế - xã hội của cá nhân",
    "solar energy": "năng lượng mặt trời dồi dào",
    "specific knowledge": "kiến thức chuyên sâu đặc thù",
    "specific sense": "theo một hàm ý cụ thể",
    "specifically designed": "được thiết kế chuyên biệt theo yêu cầu",
    "standardized testing": "thi cử / kiểm tra chuẩn hóa",
    "store data": "lưu trữ dữ liệu an toàn",
    "store information": "lưu trữ thông tin có hệ thống",
    "strain on public resources": "gánh nặng lên các nguồn lực công",
    "stress level": "mức độ căng thẳng tinh thần",
    "strongly agree": "hoàn toàn đồng tình với quan điểm",
    "substantial amount": "một lượng lớn / đáng kể",
    "substantial difference": "sự khác biệt rất lớn về bản chất",
    "substantial evidence": "chứng cứ xác thực, đầy sức nặng",
    "substantial number": "một số lượng lớn đáng kể",
    "successful implementation": "triển khai thực thi thành công mỹ mãn",
    "superior performance": "hiệu suất vượt trội hơn hẳn",
    "take initiative": "chủ động tiên phong nắm bắt cơ hội",
    "take precedence": "chiếm ưu tiên hàng đầu / được ưu tiên trước",
    "technological advances": "những bước tiến bộ vượt bậc của công nghệ",
    "technological innovation": "đổi mới sáng tạo trong công nghệ",
    "technological progress": "tiến trình phát triển của công nghệ",
    "theoretical analysis": "phân tích dựa trên nền tảng lý thuyết",
    "theoretical approach": "cách tiếp cận dựa trên lý luận",
    "theoretical basis": "cơ sở lý luận vững chắc",
    "theoretical concept": "khái niệm mang tính lý thuyết trừu tượng",
    "theoretical understanding": "sự hiểu biết sâu về mặt lý thuyết",
    "traditional approach": "cách tiếp cận theo lề lối truyền thống",
    "transferable skill": "kỹ năng có thể áp dụng linh hoạt vào nhiều công việc",
    "transport system": "hệ thống mạng lưới giao thông",
    "universally accepted": "được thừa nhận rộng rãi trên toàn cầu",
    "urban area": "khu vực đô thị sầm uất",
    "urban design": "quy hoạch và thiết kế kiến trúc đô thị",
    "urban development": "tiến trình phát triển và hiện đại hóa đô thị",
    "urban environment": "môi trường sống tại các đô thị",
    "useful information": "thông tin hữu ích, có giá trị ứng dụng",
    "vast amount": "một số lượng vô cùng khổng lồ",
    "virtual community": "cộng đồng trực tuyến trên không gian mạng",
    "vital importance": "tầm quan trọng sống còn, mang tính quyết định",
    "vital part": "bộ phận cốt yếu không thể tách rời",
    "vulnerable group": "nhóm đối tượng yếu thế, dễ bị tổn thương",
    "welfare reform": "cải cách hệ thống chính sách phúc lợi",
}

print(f"Total curated Vietnamese entries: {len(VIETNAMESE_CURATED)}")
