#!/usr/bin/env python3
"""
Unit tests for the phoneme model manifest.

Validates the generated model-manifest.json against the JSON Schema and
checks that quality thresholds, benchmark metrics, and engine verdict
are present and within expected ranges.

If the manifest file does not exist (it is generated by the benchmark
script), all tests are skipped gracefully.
"""

from __future__ import annotations

import json
import os
import sys
import unittest
from pathlib import Path

# Resolve paths relative to the workspace root
WORKSPACE_ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = WORKSPACE_ROOT / "backend" / "phoneme_service" / "model-manifest.json"
SCHEMA_PATH = WORKSPACE_ROOT / "backend" / "phoneme_service" / "model-manifest.schema.json"

# Valid engine choices
VALID_ENGINES = {"torch", "onnx", "provider-evaluation-required"}


def _load_json(path: Path) -> dict | None:
    """Load a JSON file or return None if it doesn't exist."""
    if not path.exists():
        return None
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def _skip_if_no_manifest(func):
    """Decorator: skip the test if the manifest file is absent."""
    def wrapper(self, *args, **kwargs):
        if not MANIFEST_PATH.exists():
            self.skipTest(
                f"Manifest not found at {MANIFEST_PATH} — "
                "run phoneme_model_probe.py first."
            )
        return func(self, *args, **kwargs)
    wrapper.__name__ = func.__name__
    wrapper.__doc__ = func.__doc__
    return wrapper


class TestPhonemeModelManifest(unittest.TestCase):
    """Validate the phoneme model manifest file."""

    # ------------------------------------------------------------------
    # Setup
    # ------------------------------------------------------------------

    @classmethod
    def setUpClass(cls):
        cls.manifest = _load_json(MANIFEST_PATH)
        cls.schema = _load_json(SCHEMA_PATH)

    # ------------------------------------------------------------------
    # Schema validation
    # ------------------------------------------------------------------

    @_skip_if_no_manifest
    def test_manifest_is_valid_json(self):
        """Manifest should be a valid JSON object."""
        self.assertIsInstance(self.manifest, dict, "Manifest must be a JSON object.")

    @_skip_if_no_manifest
    def test_validate_against_schema(self):
        """Manifest should validate against the JSON Schema (if jsonschema is installed)."""
        try:
            import jsonschema
        except ImportError:
            self.skipTest("jsonschema package not installed — skipping schema validation.")

        self.assertIsNotNone(self.schema, "Schema file must exist for validation.")
        try:
            jsonschema.validate(instance=self.manifest, schema=self.schema)
        except jsonschema.ValidationError as exc:
            self.fail(f"Manifest failed schema validation: {exc.message}")

    # ------------------------------------------------------------------
    # Engine verdict
    # ------------------------------------------------------------------

    @_skip_if_no_manifest
    def test_selected_engine_is_valid(self):
        """selectedEngine must be one of the allowed values."""
        engine = self.manifest.get("selectedEngine")
        self.assertIn(
            engine,
            VALID_ENGINES,
            f"selectedEngine '{engine}' is not in {VALID_ENGINES}",
        )

    @_skip_if_no_manifest
    def test_verdict_is_valid(self):
        """verdict must be one of the allowed values."""
        verdict = self.manifest.get("verdict")
        self.assertIn(
            verdict,
            VALID_ENGINES,
            f"verdict '{verdict}' is not in {VALID_ENGINES}",
        )

    @_skip_if_no_manifest
    def test_verdict_matches_selected_engine(self):
        """The deployable engine must always match the benchmark verdict."""
        self.assertEqual(self.manifest.get("verdict"), self.manifest.get("selectedEngine"))
        if self.manifest.get("evidenceStatus") != "verified":
            self.assertEqual(self.manifest.get("verdict"), "provider-evaluation-required")

    # ------------------------------------------------------------------
    # Quality thresholds
    # ------------------------------------------------------------------

    @_skip_if_no_manifest
    def test_quality_section_exists(self):
        """quality object must be present."""
        self.assertIn("quality", self.manifest, "Missing 'quality' section.")

    @_skip_if_no_manifest
    def test_mean_phoneme_confidence_range(self):
        """meanPhonemeConfidence must be between 0 and 1."""
        quality = self.manifest.get("quality", {})
        val = quality.get("meanPhonemeConfidence")
        self.assertIsNotNone(val, "meanPhonemeConfidence is required.")
        self.assertGreaterEqual(val, 0, "meanPhonemeConfidence must be >= 0.")
        self.assertLessEqual(val, 1, "meanPhonemeConfidence must be <= 1.")

    @_skip_if_no_manifest
    def test_min_nucleus_confidence_range(self):
        """minNucleusConfidence must be between 0 and 1."""
        quality = self.manifest.get("quality", {})
        val = quality.get("minNucleusConfidence")
        self.assertIsNotNone(val, "minNucleusConfidence is required.")
        self.assertGreaterEqual(val, 0, "minNucleusConfidence must be >= 0.")
        self.assertLessEqual(val, 1, "minNucleusConfidence must be <= 1.")

    # ------------------------------------------------------------------
    # Benchmark metrics
    # ------------------------------------------------------------------

    @_skip_if_no_manifest
    def test_benchmark_section_exists(self):
        """benchmark object must be present."""
        self.assertIn("benchmark", self.manifest, "Missing 'benchmark' section.")

    @_skip_if_no_manifest
    def test_peak_rss_is_present(self):
        """peakRssGiB is positive only after a verified benchmark."""
        bm = self.manifest.get("benchmark", {})
        val = bm.get("peakRssGiB")
        if self.manifest.get("evidenceStatus") == "verified":
            self.assertIsNotNone(val, "peakRssGiB is required.")
            self.assertGreater(val, 0, "peakRssGiB must be positive.")
        else:
            self.assertIsNone(val, "Unverified benchmark metrics must not contain invented values.")

    @_skip_if_no_manifest
    def test_candidate_uses_verified_upstream_artifact_identity(self):
        self.assertEqual(self.manifest.get("modelRevision"), "ae45363bf3413b374fecd9dc8bc1df0e24c3b7f4")
        self.assertEqual(self.manifest.get("tokenizerChecksum"), "d732ab2456c0c017930001dc9af0b41b3b93d25b2eb9740bf9d925508d7d87d0")
        self.assertEqual(self.manifest.get("modelChecksum"), "3173bde9e9ce490fa0f989e413c42f25bc1820c020adc1e6b9b87025b3cfcc5e")

    @_skip_if_no_manifest
    def test_mandatory_words_total_is_six(self):
        """mandatoryWordsTotal must be 6 (if present)."""
        bm = self.manifest.get("benchmark", {})
        total = bm.get("mandatoryWordsTotal")
        if total is not None:
            self.assertEqual(total, 6, "mandatoryWordsTotal must be 6.")

    @_skip_if_no_manifest
    def test_mandatory_words_correct_range(self):
        """mandatoryWordsCorrect must be 0-6 (if present)."""
        bm = self.manifest.get("benchmark", {})
        correct = bm.get("mandatoryWordsCorrect")
        if correct is not None:
            self.assertGreaterEqual(correct, 0)
            self.assertLessEqual(correct, 6)

    # ------------------------------------------------------------------
    # Required string fields
    # ------------------------------------------------------------------

    @_skip_if_no_manifest
    def test_model_id_present(self):
        """modelId must be a non-empty string."""
        val = self.manifest.get("modelId")
        self.assertIsInstance(val, str)
        self.assertTrue(len(val) > 0, "modelId must not be empty.")

    @_skip_if_no_manifest
    def test_model_revision_present(self):
        """modelRevision must be a non-empty string."""
        val = self.manifest.get("modelRevision")
        self.assertIsInstance(val, str)
        self.assertTrue(len(val) > 0, "modelRevision must not be empty.")

    @_skip_if_no_manifest
    def test_schema_version_present(self):
        """schemaVersion must be a non-empty string."""
        val = self.manifest.get("schemaVersion")
        self.assertIsInstance(val, str)
        self.assertTrue(len(val) > 0, "schemaVersion must not be empty.")

    @_skip_if_no_manifest
    def test_checksums_present(self):
        """tokenizerChecksum and modelChecksum must be non-empty strings."""
        for field in ("tokenizerChecksum", "modelChecksum"):
            val = self.manifest.get(field)
            self.assertIsInstance(val, str, f"{field} must be a string.")
            self.assertTrue(len(val) > 0, f"{field} must not be empty.")


if __name__ == "__main__":
    unittest.main()
