apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bel-presentation-demo
  annotations:
    run.googleapis.com/ingress: internal-and-cloud-load-balancing
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "4"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 3600
      containers:
        - image: REGION-docker.pkg.dev/PROJECT/bel/presentation-demo:TAG
          ports:
            - containerPort: 8080
